migrate_up:
	migrate -path database/migrations -database 'postgres://postgres:347389@localhost:5436/golobe_db?sslmode=disable' up
migrate_down:
	migrate -path database/migrations -database 'postgres://postgres:347389@localhost:5436/golobe_db?sslmode=disable' down